# Generated by Django 6.0.5 on 2026-05-17 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rating',
            new_name='app_rating_user_id_d94130_idx',
            old_name='app_rat_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='rating',
            new_name='app_rating_copy_id_c1bec0_idx',
            old_name='app_rat_copy_id_idx',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'copy')},
        ),
    ]
